version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - gscore

  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    networks:
      - gscore

  redis_insight:
    image: redislabs/redisinsight
    container_name: redis_insight
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS= ${REDIS_HOST}
    env_file:
      - .env
    ports:
      - 5540:5540
    volumes:
      - redis:/db

volumes:
  postgres:
  redis:

networks:
  gscore:
    driver: bridge
